<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smartHome" nsURI="http://www.eclipse.org/mdt/ocl/oclinecore/smartHome"
    nsPrefix="smartHome">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alarm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highTemp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heaters" ordered="false"
        upperBound="-1" eType="#//Heater" containment="true" eOpposite="#//Heater/room">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doors" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Door" containment="true" eOpposite="#//Door/room">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="windows" ordered="false"
        upperBound="-1" eType="#//Window" containment="true" eOpposite="#//Window/room">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lights" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Light" containment="true" eOpposite="#//Light/room">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Alarm_Uweight" upperBound="3"
        eType="#//WeightedProb" transient="true" defaultValueLiteral="0.178 , 0.363 , 0.597 , 0.768"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heater" eSuperTypes="#//Prob_Factor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="highTempAlarm"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="highTempAlarm" value="&#xA;&#x9;&#x9;if self.temp>=room.highTemp then&#xA;&#x9;&#x9;room.alarm=true &#xA;&#x9;&#x9;else room.alarm=false &#xA;&#x9;&#x9;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Uweight" upperBound="3"
        eType="#//WeightedProb" transient="true" defaultValueLiteral="0.257 , 0.483 , 0.619 , 0.809"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" eOpposite="#//Room/heaters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Window" eSuperTypes="#//Prob_Factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Uweight" upperBound="3"
        eType="#//WeightedProb" transient="true" defaultValueLiteral="0.187 , 0.289 , 0.6 , 0.796"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" eOpposite="#//Room/windows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Door" eSuperTypes="#//Prob_Factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Uweight" upperBound="3"
        eType="#//WeightedProb" volatile="true" transient="true" defaultValueLiteral="0.184 , 0.264 , 0.606 , 0.793"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" eOpposite="#//Room/doors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Home">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false" upperBound="-1"
        eType="#//Room" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Light" eSuperTypes="#//Prob_Factor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="doorOpen"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="doorOpen" value="&#xA;&#x9;&#x9;if door.isOpen=true then self.isON=true else self.isON=false endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" eOpposite="#//Room/lights"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Uweight" upperBound="3"
        eType="#//WeightedProb" transient="true" defaultValueLiteral="0.193 , 0.369 , 0.958 , 0.758"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="door" eType="#//Door"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prob_Factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CF" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="WeightedProb" instanceClassName="java.lang.Real">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="enumeration" value="w1 w2 w3 w4"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
